routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/
Route::auth();
Route::get('/logout', 'Auth\LoginController@logout');
Route::group(['middleware' => ['auth']], function () {
    
    /**
     * Main
     */
        Route::get('/', 'PagesController@dashboard');
        Route::get('dashboard', 'PagesController@dashboard')->name('dashboard');
        
    /**
     * Users
     */
    Route::group(['prefix' => 'users'], function () {
        Route::get('/data', 'UsersController@anyData')->name('users.data');
        Route::get('/taskdata/{id}', 'UsersController@taskData')->name('users.taskdata');
        Route::get('/leaddata/{id}', 'UsersController@leadData')->name('users.leaddata');
        Route::get('/clientdata/{id}', 'UsersController@clientData')->name('users.clientdata');
        Route::get('/users', 'UsersController@users')->name('users.users');
    });
        Route::resource('users', 'UsersController');

	 /**
     * Roles
     */
        Route::resource('roles', 'RolesController');
    /**
     * Clients
     */
    Route::group(['prefix' => 'clients'], function () {
        Route::get('/data', 'ClientsController@anyData')->name('clients.data');
        Route::post('/create/cvrapi', 'ClientsController@cvrapiStart');
        Route::post('/upload/{id}', 'DocumentsController@upload');
        Route::patch('/updateassign/{id}', 'ClientsController@updateAssign');
    });
        Route::resource('clients', 'ClientsController');
	    Route::resource('documents', 'DocumentsController');
	
      
    /**
     * Tasks
     */
    Route::group(['prefix' => 'tasks'], function () {
        Route::get('/data', 'TasksController@anyData')->name('tasks.data');
        Route::patch('/updatestatus/{id}', 'TasksController@updateStatus');
        Route::patch('/updateassign/{id}', 'TasksController@updateAssign');
        Route::post('/updatetime/{id}', 'TasksController@updateTime');
    });
        Route::resource('tasks', 'TasksController');

    /**
     * Leads
     */
    Route::group(['prefix' => 'leads'], function () {
        Route::get('/data', 'LeadsController@anyData')->name('leads.data');
        Route::patch('/updateassign/{id}', 'LeadsController@updateAssign');
        Route::patch('/updatestatus/{id}', 'LeadsController@updateStatus');
        Route::patch('/updatefollowup/{id}', 'LeadsController@updateFollowup')->name('leads.followup');
    });
        Route::resource('leads', 'LeadsController');
        Route::post('/comments/{type}/{id}', 'CommentController@store');
    /**
     * Settings
     */
    Route::group(['prefix' => 'settings'], function () {
        Route::get('/', 'SettingsController@index')->name('settings.index');
        Route::patch('/permissionsUpdate', 'SettingsController@permissionsUpdate');
        Route::patch('/overall', 'SettingsController@updateOverall');
    });

    /**
     * Departments
     */
        Route::resource('departments', 'DepartmentsController'); 

    /**
     * Integrations
     */
    Route::group(['prefix' => 'integrations'], function () {
        Route::get('Integration/slack', 'IntegrationsController@slack');
    });
        Route::resource('integrations', 'IntegrationsController');

    /**
     * Notifications
     */
    Route::group(['prefix' => 'notifications'], function () {
        Route::post('/markread', 'NotificationsController@markRead')->name('notification.read');
        Route::get('/markall', 'NotificationsController@markAll');
        Route::get('/{id}', 'NotificationsController@markRead');
    });

    /**
     * Invoices
     */
    Route::group(['prefix' => 'invoices'], function () {
        Route::post('/updatepayment/{id}', 'InvoicesController@updatePayment')->name('invoice.payment.date');
        Route::post('/reopenpayment/{id}', 'InvoicesController@reopenPayment')->name('invoice.payment.reopen');
        Route::post('/sentinvoice/{id}', 'InvoicesController@updateSentStatus')->name('invoice.sent');
        Route::post('/newitem/{id}', 'InvoicesController@newItem')->name('invoice.new.item');
    });
        Route::resource('invoices', 'InvoicesController');
});

resources/views/pages/dashboard.blade.php
@extends('layouts.mainframe')

@section('content')
@push('scripts')
    <script>
        $(document).ready(function () {
            $('[data-toggle="tooltip"]').tooltip(); //Tooltip on icons top

            $('.popoverOption').each(function () {
                var $this = $(this);
                $this.popover({
                    trigger: 'hover',
                    placement: 'left',
                    container: $this,
                    html: true,

                });
            });
        });
    </script>
@endpush
<div class="row">
    <div class="col-lg-3">
        <!-- Members online -->
        <div class="panel bg-indigo-300">
            <div class="panel-body">
                <h3 class="no-margin">
                    @foreach($taskCompletedThisMonth as $thisMonth)
                    {{$thisMonth->total}}
                    @endforeach
                </h3>
                {{ __('Tasks completed this month') }}
                <div class="text-size-small">
                    <a href="{{route('tasks.index')}}" class="text-muted ">{{ __('All Tasks') }} 
                        <i class="fa fa-arrow-circle-right"></i>
                    </a>
                </div>
            </div>

            <div class="container-fluid">
                <div id="members-online"></div>
            </div>
        </div>
        <!-- /members online -->
    </div>
    <div class="col-lg-3">
        <!-- Members online -->
        <div class="panel bg-pink-400">
            <div class="panel-body">
                <h3 class="no-margin">
                    @foreach($leadCompletedThisMonth as $thisMonth)
                    {{$thisMonth->total}}
                    @endforeach
                </h3>
                {{ __('Leads completed this month') }}
                <div class="text-size-small">
                    <a href="{{route('leads.index')}}" class="text-muted ">{{ __('All Leads') }} 
                    </a>
                </div>
            </div>

            <div class="container-fluid">
                <div id="members-online"></div>
            </div>
        </div>
        <!-- /members online -->

    </div>
    <div class="col-lg-3">
        <!-- Members online -->
        <div class="panel bg-slate">
            <div class="panel-body">
                <h3 class="no-margin">
                    {{$totalClients}}
                </h3>
                {{ __('All Clients of the system') }} 
                <div class="text-size-small">
                    <a href="{{route('clients.index')}}" class="text-muted ">{{ __('All Clients') }} 
                        <i class="fa fa-arrow-circle-right"></i>
                    </a>
                </div>
            </div>

            <div class="container-fluid">
                <div id="members-online"></div>
            </div>
        </div>
        <!-- /members online -->

    </div>
    <div class="col-lg-3">
        <!-- Members online -->
        <div class="panel bg-green-300">
            <div class="panel-body">
                <h3 class="no-margin">
                    @foreach($totalTimeSpent[0] as $sum => $value)

                    {{$value}}
                    @endforeach
                    @if($value == "")
                    0
                    @endif
                </h3>
                {{ __('Total hours registered') }}
                <div class="text-size-small">
                    <a href="#" class="text-muted ">{{ __('More info') }} 
                        <i class="fa fa-arrow-circle-right"></i>
                    </a>
                </div>
            </div>

            <div class="container-fluid">
                <div id="members-online"></div>
            </div>
        </div>
        <!-- /members online -->

    </div>
</div>

<?php $createdTaskEachMonths = array();?>
@foreach($createdTasksMonthly as $key => $task)
    <?php $createdTaskEachMonths[$key]['date'] = date('m/d/y', strTotime($task->created_at)) ?>
    <?php $createdTaskEachMonths[$key]['alpha'] = $task->day ?>
@endforeach


<?php $completedTaskEachMonths = array();?>
@foreach($completedTasksMonthly as $key => $task)
    <?php $completedTaskEachMonths[$key]['date'] = date('m/d/y', strTotime($task->updated_at)) ?>
    <?php $completedTaskEachMonths[$key]['alpha'] = $task->day ?>
@endforeach

<?php $completedLeadEachMonths = array(); $leadsCompleted = array();?>
@foreach($completedLeadsMonthly as $leads)
    <?php $completedLeadEachMonths[] = date('F', strTotime($leads->updated_at)) ?>
    <?php $leadsCompleted[] = $leads->month;?>
@endforeach

<?php $createdLeadEachMonths = array(); $leadCreated = array();?>
@foreach($createdLeadsMonthly as $lead)
    <?php $createdLeadEachMonths[] = date('F', strTotime($lead->created_at)) ?>
    <?php $leadCreated[] = $lead->month;?>
@endforeach


    @include('partials.dashboardone')

@endsection